namespace MyInterpreter.Lexer.Tokens
{
    public enum TokenType
    {
        NUMBER, TEXT,
        WHILE, FOR, IF, ELSE, RETURN, 
        INT, STRING, VOID, MATRIX,
        IDENTIFIER,
        EOT,
        AND, OR, NOT,
        PLUS, MINUS, MULTIPLY, DIVIDE, MODULO, ASSIGN,
        PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MODULO_ASSIGN,
        EQUALS, NOT_EQUAL, GREATER, LESS, GREATER_EQUAL, LESS_EQUAL,
        PAREN_OPEN, PAREN_CLOSE,
        BRACE_OPEN, BRACE_CLOSE,
        BRACKET_OPEN, BRACKET_CLOSE,
        COLON, SEMICOLON, COMMA

    }
}